# Default values for todo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  backendUrl: "http://todo-app-backend:8000"

# Individual chart values can be overridden here
backend:
  replicaCount: 1
  image:
    repository: todo-backend
    pullPolicy: Never  # Local Minikube image use karega
    tag: "latest"
  service:
    type: ClusterIP
    port: 8000

frontend:
  replicaCount: 1
  image:
    repository: todo-frontend
    pullPolicy: Never  # Local Minikube image use karega
    tag: "latest"
  service:
    type: LoadBalancer  # Random free port uthayega (No conflict)
    port: 80